name: "Draft new release"

# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         description: 'The version you want to release.'
#         required: true
on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: 'Release type'
        options:
        - major
        - minor
        - patch
        default: patch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: echo
      run: | 
        echo "Release type is ${{ github.event.inputs.release-type }}"

    - name: ensure-label
      run: |
        LABEL=$(gh api "repos/${{ github.repository }}/labels" --jq '.[] | select(.name == "auto-release")')
        if [ -z "$LABEL" ]; then
          echo "Label doesn't exist - creating"
          gh api "repos/${{ github.repository }}/labels" --silent -f name="auto-release" -f color="D4C5F9" -f description="This pull request was automatically created as part of the release process"
        else
          echo "Label exists"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}